### PR TITLE
feat: Header & Footer Component (Responsive)

### PR DESCRIPTION
**Pull request by marcmillie**
Accidentally pushed up both tickets below to the same branch.

MIAC41EHA-5 | Front-End: Header Component (Responsive)
MIAC41EHA-6 | Front-End: Footer Component (Responsive)

### CODE REVIEW

**Comment by calebcross** [comment]
Looks like you are uploading the node_modules

**Comment by marcmillie** [comment]
@calebcross Thanks for heads up. Nodes was successfully removed.

**Review by calebcross — APPROVED** [review]
Looks good!

**Review by ashmarieg — COMMENTED** [review]
approved Marcus's PR

**Pull request merged**
